### PR TITLE
fixed issue #113

### PR DESCRIPTION
**Pull request by Shikhar253**
issue #113

### CODE REVIEW

**Comment by Shikhar253** [comment]
https://user-images.githubusercontent.com/55344241/156176186-8cde6915-eead-45ea-937e-3c6078cffadf.mp4

**Comment by Shikhar253** [comment]
@Tess-Vanta can you look into it?

**Comment by Tess-Vanta** [comment]
> @Tess-Vanta can you look into it?

Merged!

**Comment by SaraswatGit** [comment]
@Shikhar253  Maybe it was mistake on her part , I have assigned the labels .

**Pull request merged**
