### PR TITLE
Fixed the size of text area during editing note description

### LINKED ISSUE #164: Size of text-area during editing note descri[tion should not reduce
image

The size of the text-area (when editing reduces) but it should match the size of text present in it . 
image

### PR DESCRIPTION
**Pull request by nitishsaini706**
fixed #164

### CODE REVIEW

**Comment by Tess-Vanta** [comment]
@nitishsaini706 Could you attach a screenshot or a video which would depict the changes you made?

**Comment by nitishsaini706** [comment]
@Tess-Vanta 
Sure, should I attach here in comment

**Comment by Tess-Vanta** [comment]
Yes here

**Comment by nitishsaini706** [comment]
Not able to add height of text area so hard coded height to 5-6 rows 
Capture

TO this 
changes2

**Pull request merged**
