### PR TITLE
changes made in task and progress section slider

### PR DESCRIPTION
**Pull request by Shlok1999**
Added a classname to Slider and removed width from Box style
Screenshot from 2022-03-11 21-38-53

https://user-images.githubusercontent.com/47269110/158030970-c4b16c38-9b7c-4c45-a612-2dd9e1015161.mp4

@Tess-Vanta Video is added

### CODE REVIEW

**Comment by Tess-Vanta** [comment]
Could you attach a video of the behavior of the page when resizing ?

**Comment by SaraswatGit** [comment]
@Shlok1999  Can u show the page at its max screen width (a image would be fine ) , have u changed the pattern ? like originally 5-6 cards came onone line have u changed it , if yes please keep at as before for max-width screen . only change it for smaller screen .

**Comment by Shlok1999** [comment]
@SaraswatGit the cards overlapped earlier , so i changed the width and adjusted some space between them
Screenshot from 2022-03-13 13-26-37
.

**Comment by SaraswatGit** [comment]
@Shlok1999  Please reduce the width of the cards on the max-width screen try to fit in at least fours cards in a line and reduce the width of the cards .

**Comment by SaraswatGit** [comment]
@Shlok1999  Please resolve this issue . 
image
And attach a latest picture of the calendar page at max width with he changes discussed a while earlier . otherwise seems awesome ! .

**Pull request closed without merging**
